package com.panpal;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller	// This means that this class is a Controller
@RequestMapping(path="/building") // This means URL's start with /building (after Application path)
public class BuildingController {
	@Autowired // This means to get the bean called userRepository
			   // Which is auto-generated by Spring, we will use it to handle the data
	private BuildingRepository buildingRepository;

	@PostMapping(path="/add") // Map ONLY POST Requests
	public @ResponseBody String addNewBuilding (@RequestParam String name
			, @RequestParam String location) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request

		Building n = new Building();
		n.setName(name);
		n.setLocation(location);
		buildingRepository.save(n);
		return "Building Saved";
	}

	@GetMapping(path="/all")
	public @ResponseBody Iterable<Building> getAllBuildings() {
		// This returns a JSON or XML with the buildings
		return buildingRepository.findAll();
	}
}
